services:
  app:
    container_name: homelab-app
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "${APP_PORT}"
    environment:
      NODE_ENV: production
      PORT: ${APP_PORT}
    networks:
      app-network:
          ipv4_address: 172.27.0.3
      db-network:
          ipv4_address: 172.28.0.3
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${APP_PORT}/api/health > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    container_name: homelab-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    environment:
      APP_PORT: ${APP_PORT}
      DOMAIN: ${DOMAIN}
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      proxy-network:
          ipv4_address: 172.26.0.3
      app-network:
          ipv4_address: 172.27.0.4
      admin-network:
          ipv4_address: 172.29.0.3
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  postgres:
    image: postgres:16.11-alpine3.22
    container_name: homelab-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
      # - ../../.env.development.local
    volumes:
      - pg_volume:/var/lib/postgresql/data:rw
      - ./postgres/postgres.conf:/etc/postgresql/postgresql.conf:ro
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d:ro
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "log_statement=none", "-c", "log_min_duration_statement=1000", "-c", "log_connections=on", "-c", "log_disconnections=on" ]
    user: "70:70" # Postgres user
    healthcheck:
      test: [ "CMD-SHELL", 'pg_isready -U "$${POSTGRES_USER:-postgres}" -d "$${POSTGRES_DB:-postgres}" -h localhost || exit 1' ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    stop_grace_period: 120s
    networks:
      db-network:
        ipv4_address: 172.28.0.2

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - .env
      # - ../../.env.development.local
    volumes:
      - pgadmin_volume:/var/lib/pgadmin:rw
    depends_on:
      - postgres
    networks:
      db-network:
          ipv4_address: 172.28.0.4
      admin-network:
        ipv4_address: 172.29.0.4

volumes:
  homelab-data:
  pg_volume:
    driver: local
  pgadmin_volume:
    driver: local

networks:
  admin-network:
    name: homelab-admin
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24
          gateway: 172.29.0.1
   # Réseau exposé uniquement au reverse proxy.
  proxy-network:
    name: proxy-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/24
          gateway: 172.26.0.1

  # Communication Nginx <-> App.
  app-network:
    name: app-network
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.27.0.0/24
          gateway: 172.27.0.1

  # Communication App <-> PostgreSQL <-> pgAdmin.
  db-network:
    name: db-network
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1