events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    upstream next_app {
        server app:${APP_PORT};
    }

    upstream pg_admin {
        server pgadmin:80;
    }

    include /etc/nginx/conf.d/*.conf;
}
